front_GestionProyectos/routes/route.py
from flask import Blueprint, render_template, request, redirect, url_for, jsonify
import requests
import json
router = Blueprint('router', __name__)
BASE_URL = 'http://localhost:8080/myapp/'

@router.route('/')
def home():
    return render_template('home.html')
@router.route('/page1')
def page1():
    return "This is Page 1"

@router.route('/page2')
def page2():
    return "This is Page 2"

front_GestionProyectos/routes/route_inversionistas.py
from flask import Blueprint, json, render_template, request, redirect, url_for, flash
import requests

route_inversionistas = Blueprint('route_inversionistas', __name__)

URL = 'http://localhost:8080/myapp/inversionistas/'

@route_inversionistas.route('/inversionistas')
def view_inversionistas():
    r = requests.get(URL + 'all')
    print(r.json())  
    data = r.json().get('data')
    return render_template('parts/inversionistas.html', inversionistas=data)

@route_inversionistas.route('/inversionistas/registro')
def registro_inversionista():
    return render_template('forms/inversionistas/registroinversionistas.html')

@route_inversionistas.route('/inversionistas/registro/save', methods=["POST"])
def save_inversionista():
    headers = {'Content-Type': 'application/json'}
    form = request.form
    dataForm = {
        "nombre": form["nombre"],
        "apellido": form["apellido"],
        "email": form["email"],
        "Identification": form["Identification"]
    }
    r = requests.post(URL + 'save', data=json.dumps(dataForm), headers=headers)

    if r.status_code == 200:
        flash('Inversionista registrado correctamente', category='info')
    else:
        flash('No se ha podido registrar al inversionista', category='error')
    return redirect('/inversionistas')

@route_inversionistas.route('/inversionistas/edit/<id>')
def update_inversionista_view(id):
    r = requests.get(URL + 'get/' + id)
    if r.status_code == 200:
        data = r.json()
        return render_template('forms/inversionistas/modificarInversionista.html', inversionista=data["data"])
    else:
        flash('No se pudo encontrar el inversionista', category='error')
        return redirect('/inversionistas')

@route_inversionistas.route('/inversionistas/edit/save', methods=["POST"])
def update_inversionista():
    headers = {'Content-Type': 'application/json'}
    form = request.form
    dataForm = {
        "id": form["id"],
        "nombre": form["nombre"],
        "apellido": form["apellido"],
        "email": form["email"],
        "Identification": form["Identification"]

    }
    r = requests.post(URL + 'update', data=json.dumps(dataForm), headers=headers)

    if r.status_code == 200:
        flash('Inversionista actualizado correctamente', category='info')
        return redirect('/inversionistas')
    else:
        flash('No se pudo actualizar el inversionista', category='error')
    return redirect('/inversionistas')

@route_inversionistas.route('/inversionistas/delete/<id>', methods=["POST"])
def delete_inversionista(id):
    headers = {'Content-Type': 'application/json'}
    dataForm = {"id": id}
    r = requests.post(URL + 'delete', data=json.dumps(dataForm), headers=headers)

    if r.status_code == 200:
        flash('Inversionista eliminado correctamente', category='info')
        return redirect('/inversionistas')
    else:
        flash('No se pudo eliminar el inversionista', category='error')
    return redirect('/inversionistas')

@route_inversionistas.route('/inversionistas/order/<algorithm>/<attribute>/<type>')
def order_inversionistas(algorithm, attribute, type):
    url = URL + 'order' + '/' + algorithm + '/' + attribute + '/' + type
    r = requests.get(url)
    print(url)

    data = r.json().get('data')
    
    if r.status_code == 200:
        flash('Inversionistas ordenados', category='info')
        print('si funca')
        return render_template('parts/inversionistas.html', inversionistas=data)
    else:
        flash(f'Error al ordenar los inversionistas. Código de estado:', category='error')
        return redirect('/inversionistas')

@route_inversionistas.route('/inversionistas/LinearSearch/<attribute>/<value>')
def search_linear(attribute, value):
    url = URL + 'buscar/LinearSearch/'  + attribute + '/' + value
    r = requests.get(url)
    print(url)
    print(r.json())  

    data = r.json().get("data")
    if r.status_code == 200:
        flash('Inversioinversionistasnistas encontrados', category='info')
        return render_template('parts/inversionistas.html', inversionistas=data)
    else:
        flash('No se encontraron resultados con la búsqueda lineal', category='info')
        return redirect('/inversionistas')

@route_inversionistas.route('/inversionistas/binarySearch/<attribute>/<value>')
def search_binary(attribute, value):
    url = URL + 'buscar/binarySearch/'  + attribute + '/' + value
    r = requests.get(url)
    print(url)

    data = r.json().get("data")
    if r.status_code == 200:
        flash('Inversioinversionistasnistas encontrados', category='info')
        return render_template('parts/inversionistas.html', inversionistas=data)
    else:
        flash('No se encontraron resultados con la búsqueda lineal', category='info')
        return redirect('/inversionistas')

front_GestionProyectos/routes/route_proyectos.py
from flask import Blueprint, json, render_template, request, redirect, url_for, flash
import requests

# Definir el Blueprint para las rutas de proyectos
route_proyectos = Blueprint('route_proyectos', __name__)

# URL del API backend (modifica según sea necesario)
URL = 'http://localhost:8080/myapp/proyectos/'

# Ruta para mostrar todos los proyectos
@route_proyectos.route('/proyectos')
def view_proyectos():
    r = requests.get(URL + 'all')
    data = r.json().get('data')
    return render_template('parts/proyectos.html', proyectos=data)

# Ruta para mostrar el formulario de registro de un proyecto
@route_proyectos.route('/proyectos/registro')
def registro_proyecto():
    return render_template('forms/proyectos/registroProyecto.html')

# Ruta para guardar un nuevo proyecto
@route_proyectos.route('/proyectos/registro/save', methods=["POST"])
def save_proyecto():
    headers = {'Content-Type': 'application/json'}
    form = request.form
    dataForm = {
        "nombre": form["nombre"],
        "fechaInicio": form["fechaInicio"],
        "fechaFin": form["fechaFin"],
        "inversion": form["inversion"],
        "tiempoVida": form["tiempoVida"],
        "energia": form["energia"]
    }
    r = requests.post(URL + 'save', data=json.dumps(dataForm), headers=headers)
    data = r.json()
    if r.status_code == 200:
        flash('Proyecto registrado correctamente', category='info')
    else:
        flash(data['data'], category='error')
    return redirect('/proyectos')

# Ruta para mostrar el formulario de edición de un proyecto
@route_proyectos.route('/proyectos/edit/<id>')
def update_proyecto_view(id):
    r = requests.get(URL + 'get/' + id)
    if r.status_code == 200:
        data = r.json()
        return render_template('forms/proyectos/modificarProyecto.html', proyecto=data["data"])
    else:
        flash('No se pudo encontrar el proyecto', category='error')
        return redirect('/proyectos')

# Ruta para actualizar un proyecto
@route_proyectos.route('/proyectos/edit/save', methods=["POST"])
def update_proyecto():
    headers = {'Content-Type': 'application/json'}
    form = request.form
    dataForm = {
        "id": form["id"],
        "nombre": form["nombre"],
        "fechaInicio": form["fechaInicio"],
        "fechaFin": form["fechaFin"],
        "inversion": form["inversion"],
        "tiempoVida": form["tiempoVida"],
        "energia": form["energia"]
    }
    r = requests.post(URL + 'update', data=json.dumps(dataForm), headers=headers)

    if r.status_code == 200:
        flash('Proyecto actualizado correctamente', category='info')
        return redirect('/proyectos')
    else:
        flash('No se pudo actualizar el proyecto', category='error')
    return redirect('/proyectos')

# Ruta para eliminar un proyecto
@route_proyectos.route('/proyectos/delete/<id>', methods=["POST"])
def delete_proyecto(id):
    headers = {'Content-Type': 'application/json'}
    dataForm = {"id": id}
    r = requests.post(URL + 'delete', data=json.dumps(dataForm), headers=headers)

    if r.status_code == 200:
        flash('Proyecto eliminado correctamente', category='info')
        return redirect('/proyectos')
    else:
        flash('No se pudo eliminar el proyecto', category='error')
    return redirect('/proyectos')

# Ruta para ordenar proyectos
@route_proyectos.route('/proyectos/order/<algorithm>/<attribute>/<type>')
def order_proyectos(algorithm, attribute, type):
    url = URL + 'order' + '/' + algorithm + '/' + attribute + '/' + type
    r = requests.get(url)
    print(url)

    data = r.json().get('data')
    if r.status_code == 200:
        
        flash('Proyectos ordenados correctamente', category='info')
        return render_template('parts/proyectos.html', proyectos=data)
    else:
        flash(f'Error al ordenar los proyectos. Código de estado: {r.status_code}', category='error')
        return redirect('/proyectos')

# Ruta para buscar proyectos con búsqueda lineal
@route_proyectos.route('/proyectos/LinearSearch/<attribute>/<value>')
def search_linear(attribute, value):
    url = URL + 'buscar/LinearSearch/'  + attribute + '/' + value
    r = requests.get(url)
    print(url)

    data = r.json().get("data")
    if r.status_code == 200:
        flash('Proyectos encontrados', category='info')
        return render_template('parts/proyectos.html', proyectos=data)
    else:
        flash('No se encontraron resultados con la búsqueda lineal', category='info')
        return redirect('/proyectos')

# Ruta para buscar proyectos con búsqueda binaria
@route_proyectos.route('/proyectos/binarySearch/<attribute>/<value>')
def search_binary(attribute, value):
    url = URL + 'buscar/binarySearch/'  + attribute + '/' + value
    r = requests.get(url)
    print(url)

    data = r.json().get("data")
    if r.status_code == 200:
        flash('Proyectos encontrados', category='info')
        return render_template('parts/proyectos.html', proyectos=data)
    else:
        flash('No se encontraron resultados con la búsqueda binaria', category='info')
        return redirect('/proyectos')

front_GestionProyectos/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}Dashboard{% endblock %}</title>

    <!-- Custom fonts for this template -->
    <link href="{{ url_for('static', filename='vendor/fontawesome-free/css/all.min.css') }}" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,300,400,600,700,800,900" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{{ url_for('static', filename='css/sb-admin-2.min.css') }}" rel="stylesheet">

    <!-- Custom styles for DataTables -->
    <link href="{{ url_for('static', filename='vendor/datatables/dataTables.bootstrap4.min.css') }}" rel="stylesheet">

    {% block extra_head %}{% endblock %}
</head>

<body id="page-top">
    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">
            <li class="nav-item active">
                <a class="nav-link" href="{{ url_for('router.home') }}">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Dashboard</span>

                </a>
                <li class="nav-item">
                    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseComponents"
                       aria-expanded="false" aria-controls="collapseComponents">
                        <i class="fas fa-fw fa-cog"></i>
                        <span>Creacion</span>
                    </a>
                    <div id="collapseComponents" class="collapse" aria-labelledby="headingComponents" data-parent="#accordionSidebar">
                        <div class="bg-white py-2 collapse-inner rounded">
                            <h6 class="collapse-header">Escoger creacion</h6>
                            <!-- Enlace para Inversionista -->
                            <a class="collapse-item" href="{{ url_for('route_inversionistas.registro_inversionista') }}">Inversionista</a>
                            <!-- Enlace para Proyecto -->
                            <a class="collapse-item" href="{{ url_for('route_proyectos.registro_proyecto') }}">Proyecto</a>
                        </div>
                        
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTables"
                       aria-expanded="false" aria-controls="collapseTables">
                        <i class="fas fa-fw fa-table"></i>
                        <span>Tables</span>
                    </a>
                    <div id="collapseTables" class="collapse" aria-labelledby="headingTables" data-parent="#accordionSidebar">
                        <div class="bg-white py-2 collapse-inner rounded">
                            <h6 class="collapse-header">Table Options:</h6>
                            <a class="collapse-item" href="{{ url_for('route_inversionistas.view_inversionistas') }}">Inversionistas</a>
                            <a class="collapse-item" href="{{ url_for('route_proyectos.view_proyectos') }}">Proyectos</a>
                        </div>
                    </div>
                </li>
                

                
            <!-- Add more navigation items here -->
        </ul>
        <!-- End of Sidebar -->

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">
                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">
                    <h1 class="h3 mb-0 text-gray-800">{% block header %}Dashboard{% endblock %}</h1>
                </nav>
                
                <!-- End of Topbar -->

                <!-- Begin Page Content -->
                <div class="container-fluid">
                 
                    
                    <!-- Example Buttons for Navigation -->


                    {% block content %}

                    {% endblock %}
                </div>
                <!-- /.container-fluid -->
            </div>
            <!-- End of Main Content -->

            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; Your Website 2024</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->
    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Bootstrap core JavaScript -->
    <script src="{{ url_for('static', filename='vendor/jquery/jquery.min.js') }}"></script>
    <script src="{{ url_for('static', filename='vendor/bootstrap/js/bootstrap.bundle.min.js') }}"></script>

    <!-- Core plugin JavaScript -->
    <script src="{{ url_for('static', filename='vendor/jquery-easing/jquery.easing.min.js') }}"></script>

    <!-- Custom scripts for all pages -->
    <script src="{{ url_for('static', filename='js/sb-admin-2.min.js') }}"></script>

    <!-- Page level plugins -->
    <script src="{{ url_for('static', filename='vendor/datatables/jquery.dataTables.min.js') }}"></script>
    <script src="{{ url_for('static', filename='vendor/datatables/dataTables.bootstrap4.min.js') }}"></script>

    <!-- Page level custom scripts -->
    <script src="{{ url_for('static', filename='js/demo/datatables-demo.js') }}"></script>

    {% block extra_scripts %}{% endblock %}
</body>

</html>

front_GestionProyectos/templates/home.html
{% extends "base.html" %}

{% block title %}Dashboard{% endblock %}

{% block header %}Panel de Control{% endblock %}

{% block content %}
<div class="row">
    <div class="col-lg-6 mb-4">
        <h3>Bienvenido al Dashboard</h3>
        <p>Contenido personalizado para esta página.</p>
    </div>
</div>
{% if message %}
    <div class="alert alert-info">{{ message }}</div>
{% endif %}

{% endblock %}